version: "3"

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3308:3308
    command: --port 3308
    tty: true

  api:
    depends_on:
      - db
    container_name: "api"
    build: ./back
    ports:
      - "8000:8000"
    volumes:
      - ./back/api:/usr/src/server

  front:
    container_name: front
    build:
      context: .
      dockerfile: ./front/Dockerfile
    ports:
      - 80:8080
    restart: always
    tty: true
    volumes:
      - ./front/app:/app