USE task_db;

DROP TABLE IF EXISTS task;


CREATE TABLE task (
    task_id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    text Text(1024) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (task_id)
);